### ISSUE TITLE
Wont show images

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [jeffreymendez1993/react-native-webview-readability#11]
Reader view removes images inside content. is there any way to show images with library

**Comment by j-mendez** [comment]
Not currently. We can easily add this in the clean-html-js dep and add a
prop here to determine specific imgs or all imgs.

**Comment by j-mendez** [comment]
https://github.com/A11yWatch/clean-html-js/blob/master/src/clean-html.ts
allowedTags on line 60. Could add a param of a method that adjust the
value. I won’t be able to do this till next week on vacation atm.

**Comment by j-mendez** [comment]
Could add a param or a config method I meant sorry.

**Comment by j-mendez** [comment]
@IbrahimCanKALYA if the html images are inline you can now use the config prop with the property `allowedTags` which accepts an array of HTML elements to allow to render. `ex: allowedTags: ['img', 'svg']`. Currently this only works if the html is feed with the resources inline.
