### ISSUE TITLE
error parsing every url

### ISSUE THREAD

**Issue by macartigan** [jeffreymendez1993/react-native-webview-readability#14]
on both ios and android

react-native-reader version : 0.5.3 and 0.3.3 and 0.3.2
"react-native": "0.64.0",
"react-native-webview": "^11.3.1",

**Comment by j-mendez** [comment]
@clind-arthur fixed in version 0.5.4. Thank you for the ticket!

**Comment by macartigan** [comment]
Thanks for your answer.
I have the same parsing error with "react-native-reader": "^0.5.4"

**Comment by j-mendez** [comment]
@clind-arthur can I get an example of the url please?

**Comment by macartigan** [comment]
> @clind-arthur can I get an example of the url please?

I have the problem for every website, like https://review.firstround.com/30-tips-for-new-startup-employees

**Comment by j-mendez** [comment]
Issue should be fixed in 0.6.10. Thank you for this ticket!
<img width="529" alt="Screen Shot 2021-04-15 at 8 29 41 PM" src="https://user-images.githubusercontent.com/8095978/114954811-501f2c00-9e29-11eb-9c3e-ade1192de204.png">

**Comment by j-mendez** [comment]
latest is now 0.6.10.

**Comment by macartigan** [comment]
yes it's work. Thanks a lot !

**Comment by sraut1** [comment]
Hey @j-mendez Thanks for great library. What could be reason if above issue is occurring just for 1 particular url but works fine for other URLs. example: https://www.ajc.com/sports/atlanta-hawks/hawks-to-hire-onsi-saleh-as-assistant-gm/5CYOP5J4GFD2FLPX3A6QN6N5PU/
