### ISSUE TITLE
deal with contentContainerStyle

### ISSUE THREAD

**Issue by macartigan** [jeffreymendez1993/react-native-webview-readability#15]
It will be nice if we can add marginVertical on the contentContainerStyle of the scrollView.

**Comment by j-mendez** [comment]
> It will be nice if we can add marginVertical on the contentContainerStyle of the scrollView.

You can use the `containerStyle` prop atm for this.

**Comment by macartigan** [comment]
contentContainerStyle and containerStyle margin is not the same. It will be nice to add margin inside the scrollView, not outside. Do I miss something ?

**Comment by j-mendez** [comment]
@clind-arthur you are right. v0.7.1 you can now use the `contentContainerStyle` property to adjust this. Thank you!
