### ISSUE TITLE
deprecated-react-native-prop-types from react-native-htmlview

### ISSUE THREAD

**Issue by ceddybi** [jeffreymendez1993/react-native-webview-readability#17]
### import ViewPropTypes from deprecated-react-native-prop-types instead of react-native 

Linked issue https://github.com/jsdf/react-native-htmlview/issues/345

**Comment by Brightness85** [comment]
any solution?

**Comment by j-mendez** [comment]
@Brightness85 Hi, most likely we need to fork the repo for the patch changes.

**Comment by Brightness85** [comment]
https://github.com/jsdf/react-native-htmlview/issues/313#issuecomment-872564166 this help me.
i used  `deprecated-react-native-prop-types` instead of 2. step to import `ViewPropTypes`

**Comment by j-mendez** [comment]
@ceddybi @Brightness85 ty for reporting the issue, fixed in `v0.9.3`.
