### ISSUE TITLE
Unable to resolve module 'rn-fast-htmlview'

### ISSUE THREAD

**Issue by harrysayers** [jeffreymendez1993/react-native-webview-readability#18]
Hi,

I've installed react-native-reader, however I'm getting an error saying it is unable to resolve module 'rn-fast-htmlview' from 'build/reader.js'. What is strange is that this package doesn't seem to exist. 

Do you know how to solve this? 

Thank you,
Harry

**Comment by j-mendez** [comment]
Hi, the package lives on npm here at https://www.npmjs.com/package/rn-fast-htmlview. Try deleting the node_modules folder and clean either the yarn.lock or package-lock.json to re-install.

**Comment by j-mendez** [comment]
The package is named ‘ react-native-fast-htmlview’.
