### ISSUE TITLE
Invariant Violation:requirenativecomponent

### ISSUE THREAD

**Issue by 16isaac89** [jeffreymendez1993/react-native-webview-readability#5]
![Capture](https://user-images.githubusercontent.com/23630466/60249546-bee66a80-98cd-11e9-9caa-3ee70e8535a6.PNG)
package.json
{
  "name": "webview",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-webview-readability": "^0.1.9"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
App.js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import ReadabilityWebView from 'react-native-webview-readability';

export default class App extends Component {
  render() {
    return (
      <ReadabilityWebView
      htmlCss={css}
      url="https://www.onlinesokoni.com/"
       title="Online Sokoni" />
    );
  }
}

const css = `
  body {
    color: #2a2a2a;
    font-family: sans-serif, Roboto, monospace;
  },
  img, figure {
    display: none;
  },
  h1 {
    border-bottom-width: 1px;
    border-color: #ccc;
    padding-bottom: 3px;
    border-bottom-style:solid;
    font-size: 1.6em;
    font-weight: bold;
    letter-spacing: .05em;
  }
  p {
    letter-spacing: .03em;
  }
`;

**Comment by j-mendez** [comment]
@16isaac89 make sure you run `react-native-link react-native-webview` or follow the getting started instructions here https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md. If you do not want to use webview as a dependency you can check out the `react-native-reader` branch https://github.com/jeffreymendez1993/react-native-webview-readability/tree/experimental/react-native-reader or just run `npm install react-native-reader` and try out the slimmed down project that is not dependent on react-native-webview. If you want to use the Webview without linking anything you can use version `0.1.1 ` which will be removed from RN core soon.

Closing the issue.
